### PR TITLE
add sourcemaps and update to latest module handling

### PR DESCRIPTION
**Pull request by jlongster**
I updated the plugin to use the "macros" option to load in global macros instead of concat'ing a string and added sourcemap support. I also changed it so that it only works with ".sjs" files, and it compiles each file individually to a corresponding ".js" file.

After looking at your repos, you seem to just use a ".js" extension, so I'm open to making this more configurable somehow. I like having ".sjs" which compiles to ".js" and ".js.map" and I get good error handling easily, though I hate that each file is now 3 files.

### CODE REVIEW

**Comment by jlongster** [comment]
Also, what do you think about changing the task name to just "sweet"? I like short names, and `grunt sweet` is easier to type :)

**Comment by natefaubion** [comment]
Thanks for the PR! There are a few things I'd like to see:
- Don't force me to use a `.sjs` extension (sweet.js itself doesn't even use it), and don't hard code the dest to the file name. I would check if the file has a `dest`, and then I would do what I was doing before and concat the `src` files, writing to the supplied `dest`. If there isn't a `dest` and its only a list of input files, then I would do what you are doing and compile each file individually. If when compiling individually, the input file has a `.js` extension already, I would compile it to `filename.compiled.js`, otherwise do what you are doing and rename it to `.js`.
- I'm ok with changing the task name, but there's already a (fairly recently maintained) grunt task called `sweet` for doing static site generation. I would probably rename it to `sweetjs` because the underscore is ugly.
- I would change the `goodNodeErrors` option to `nodeSourceMapSupport` to reflect the require that is inserted at the beginning of the file.

**Comment by jlongster** [comment]
I refactored it quite a bit according to your feedback, which I think is good. It's a little messy, and it doesn't quite work yet. From what I see, a destination _always_ exists when iterating over files. If you don't explicitly set one, if default to the name of the target, I think? For this:

``` js
        sweet_js: {
            all: {
                files: { src: ['**/*.sjs', '!node_modules/**/*.sjs'] }
            }
        }
```

The `f.dest` is set to `src`. Is my configuration wrong? Feel free to wait to merge this until we figure it out, or merge it and fix it the way you desire.

Additionally, there's one more feature I'd like: the ability to only compile files that have changed. grunt unfortunately doesn't have great support for that, and I think the recommended way of doing it is watching for the `watch` event. This must be done in the project-specific Gruntfile though, which is why I exported the compile function so I can call it like this:

``` js
    var gruntSweet = require('grunt-sweet.js');

    grunt.event.on('watch', function(action, filepath, target) {
        if(action == 'changed' && target == 'sweet') {
          gruntSweet.compile(filepath);
        }
    });
```

That seems kind of hacky though...

**Comment by natefaubion** [comment]
You are correct about the `dest`. I made a bad assumption. We can either put it behind a flag or guess. Generally, people don't use a filename as a target name (its labelled as deprecated in the docs), so I'm ok with checking if the target name (`this.name`) is the same as the `dest`. If it becomes a problem in usage, we can add a flag like `individualCompilation` or something that defaults to `true` and can be turned off.

As for watching, you are supposed to use the [`grunt-contrib-watch`](https://github.com/gruntjs/grunt-contrib-watch) plugin. You just give it files to watch and a task to execute. It also has a bunch of other fancy options like live reload. It's not something that belongs in this plugin.

Edit: sorry, I misread your comment about watching. You are right, it would compile all the files not the ones that changed. I still don't know if that belongs in the plugin, as that's a more general problem, and not really sweet.js specific. It also only really applies if you are doing individual file compilation.

**Comment by jlongster** [comment]
I don't think individual compilation will be rare at all; if you are doing this with node you will always want to do that. I don't have time for a thorough reply right now, but just wanted to say that :)

**Comment by jlongster** [comment]
Bah, sorry, I'll flesh it out. I see that your suggestion would probably work fine (checking if this.name is the same as dest) to support individual compilation.

Also, to support the special `watch` behavior all we have to do is export the `compile` function in our task. The `grunt.event.on` goes in my app-specific Gruntfile. I think it's worth doing, since I needed to separate out the `compile` function anyway (if you look at the 2 different branches that need to compile stuff). It definitely makes it faster to compile stuff in large node apps, which I intend to use macros in. I wish grunt had better support for it...

**Comment by natefaubion** [comment]
I didn't say it would be rare. Just that it only applies with that use case. I don't mind exporting the function, though.

I do think its a more general problem that could apply to more plugins, and could be spun off into its own plugin. It could listen to the watch event, and create an adhoc task with just those files as `src`s and use `grunt.task.run` to execute it.

**Comment by jlongster** [comment]
That's a valid point. When I was researching it there was some info for creating adhoc tasks but I couldn't get it to work. Perhaps we should just figure that out and not have the nasty manual call. I'll do that, but probably not until next week after Thanksgiving :)

I read your comment too quickly and when I thought you were implying that it'd be rare.

**Comment by natefaubion** [comment]
I ran an experiment and this worked:

``` js
module.exports = function(grunt) {
  grunt.registerMultiTask('foo', 'Testing', function() {
    console.log(this.name, this.files);
  });

  grunt.registerTask('bar', function() {
    var name = '$$diff';
    var tasks = grunt.config.get('foo');

    tasks[name] = ['a/b.js'];
    grunt.config.set('foo', tasks);
    grunt.task.run('foo:' + name);
  });

  grunt.initConfig({
    foo: {

    }
  });
};
```

You have to reset the config object because when you get it, it returns a copy. I used dollars, because grunt ignores tasks that start with underscores, but you could just come up with a unique name when the module is loaded to avoid name collision.

Edit: You can actually just do a set with a dot path

``` js
  grunt.registerTask('bar', function() {
    var name = '$$diff';
    var files =  ['a/b.js'];
    grunt.config.set('foo.' + name, files);
    grunt.task.run('foo:' + name);
  });
```

**Comment by jlongster** [comment]
Awesome! We should definitely rely on that and write our plugin independently then.

Another compilation option that I think I want to support is instead of writing each individual file out right beside the original one, but put them all in a "built" folder. So I could have a "src" dir that builds out to "build" that has the same directory structure, but is compiled out. I think this is more manageable for large node projects because right now every file has a .sjs, .js, and .js.map, which is very cluttered.

Anyway, I can finish implementing all this next week. Tomorrow starts vacation!

**Comment by natefaubion** [comment]
For that you should use [`grunt.file.expandMapping`](http://gruntjs.com/api/grunt.file#grunt.file.expandmapping).

``` js
grunt.initConfig({
  sweet_js: {
    all: {
      files: grunt.file.expandMapping(['src/**/*.js'], 'build')
    }
  }
})
```

Or something like that, you can configure it how you like.

Edit: Or you may just get it for free [http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically].

**Comment by jlongster** [comment]
So you were actually write about `f.dest`. It actually doesn't exist if you just do:

```
        sweet_js: {
            target: {
                src: ['**/*.sjs', '!node_modules/**/*.sjs']
            }
        }
```

I had configured it wrong. If you use `files` you're supposed to specify dest -> src mappings. Anyway, I'm working on this again and will fix it up.

**Comment by jlongster** [comment]
Ok, I think this is done. Let me know what you think. It works if you set a `dest` and concat's everything together, otherwise compiles individual files. It compiles to a `.js` file if the src ext is not that, otherwise compiles to a `.built.js` file.

**Comment by natefaubion** [comment]
I'll put out an npm release later today. I also added you as a collaborator.

**Comment by jlongster** [comment]
Cool, thanks!

**Pull request merged**
