### PR TITLE
compile multiple source files to a dest. directory.

### PR DESCRIPTION
**Pull request by nathanross**
e.g.

``` js
sweetjs: {
  main: {
    src : "src/*"
    dest : "dest/"      
  }
}
```

### CODE REVIEW

**Comment by natefaubion** [comment]
Thanks!

**Comment by natefaubion** [comment]
Am I doing something wrong? I tried this and I get an error:

`Warning: Unable to write "dest/" file (Error code: ENOENT). Use --force to continue.`

**Comment by natefaubion** [comment]
Fixed for 0.1.5

**Comment by nathanross** [comment]
the other way to do this `if(fs.lstatSync(f.dest).isDirectory())` costs a disk read but will work fine with dir paths with no end slash, just didn't want to include a module without a go ahead. it's your call. :+1:

**Comment by natefaubion** [comment]
But that requires the directory to already exist. I'm fine with the slash.

**Pull request merged**
